apiVersion: v2
name: prometheus-crds
description: Prometheus Operator CRDs (ServiceMonitor, PodMonitor, etc.)
type: application
version: 1.0.0

dependencies:
  - name: prometheus-operator-crds
    version: "18.0.0"
    repository: https://prometheus-community.github.io/helm-charts
